___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1


#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

* Вивести версію та конфігурацію бібліотеки:

In [2]:
#Виводимо версію бібліотеки
np.__version__

'1.23.5'

In [3]:
#Виводимо конфігурацію бібліотеки
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

Створити вектор з 10 елементів, заповнений одиницями:

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [5]:
np.arange(0, 11)

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [6]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [7]:
# Створюємо вектор з 20 елементів з випадковими цілими числами
Z = np.random.randint(-100, 100, size=20)
Z

array([ 99, 76, 23, 58, -38, -90, -79, -22, 79, -73, -71, 93, 34,
 -60, -91, -25, 10, -85, 2, 88])

In [8]:
# Знаходимо індекси ненульових елементів у даному векторі
np.nonzero(Z)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),)

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [9]:
# Знайти середнє значення (mean)
Z.mean()

# Знайти медіану вектора
np.median(Z)

# Знайти стандартне відхилення вектора (std)
np.std(Z)

print(f'Cереднє значення: {Z.mean()}')
print(f'Медіана: {np.median(Z)}')
print(f'Стандартне відхилення: {np.std(Z)}')

Cереднє значення: -3.6
Медіана: -10.0
Стандартне відхилення: 66.8860224561156


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [38]:
# Матриця з випадковими числами розміром 4х2
X = np.random.random((4,2))

# Матриця з випадковими числами розміром 2х2
Y = np.random.random((2,2))

#Перемножуємо матриці X та Y

Z = np.matmul(X, Y)
Z

array([[0.10223421, 0.14977903],
 [0.29422778, 0.40526266],
 [0.38104356, 0.55102558],
 [0.44703632, 0.64484854]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [39]:
# Вектором вважають матрицю яка містить один рядок чи один стовбець. Перетворюємо матрицю Z у вектор:

Z1 = Z.reshape((1, Z.size))
print(Z1)

#Знайти мінімальне та максимальне значення

min_value = np.min(Z1)
max_value = np.max(Z1)

print(f'Мінімальне значення: {min_value}')
print(f'Максимальне значення: {max_value}')

[[0.10223421 0.14977903 0.29422778 0.40526266 0.38104356 0.55102558
  0.44703632 0.64484854]]
Мінімальне значення: 0.10223420885883737
Максимальне значення: 0.6448485443357376


In [40]:
# Максимальне значення замінити на 0:

inx_max = np.argmax(Z1) # знаходимо індекс максимального числа

Z1[0, inx_max] = 0 # Присвоюємо значення 0 максимальному числу за індексом

# Виводимо результат:
Z1

array([[0.10223421, 0.14977903, 0.29422778, 0.40526266, 0.38104356,
 0.55102558, 0.44703632, 0. ]])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [13]:
c1 = np.correlate(Z[0], Z[1]) # кореляцію першого рядка матриці Z[0] з другим рядком Z[1]
c2 = np.correlate(Z[0], Z[2]) # кореляцію першого рядка матриці Z[0] з третім рядком Z[2]
c3 = np.correlate(Z[0], Z[3]) # кореляцію першого рядка матриці Z[0] з четвертм рядком Z[3]

print(c1 , c2, c3)

[0.64385956] [0.22387528] [0.15198033]


Дано матрицю. Знайти ранг матриці:

In [14]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

# Знайти ранг матриці:
rank = np.linalg.matrix_rank(a)
rank

3

Знайти визначник матриці:

In [15]:
#Визначником n –го порядку матриці A називається алгебраїчна сума всіх можливих добутків її елементів

np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [16]:
#Знаходимо за допомогою функції numpy.linalg.eig()

w, v = np.linalg.eig(a) # функція виводить спочатку масив власних значеннь w і масив власних векторів v

print(f'Власні значення: {w}')
print(f'Власні вектори: {v}')

Власні значення: [14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
Власні вектори: [[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [32]:
a = np.random.randint(0,10,50)

# Функія bincount() повертає кількість входжень значень в масив 

np.bincount(a) # - виводить масив з кількістю входження кожного елемента

# Фунція .argmax виводить індекс максимального елемента з масиву

np.argmax(np.bincount(a)) 
#оскільки на всіх функція argmax приймає масив зі наченнями частот повторення чисел, тому ми отримуємо індекс числа яке повторюється в масиві а найбільшу кількість раз

#Результат

a[np.argmax(np.bincount(a))]

6

Виведіть лише парні числа, що діляться на 5:

In [33]:
a = np.random.randint(0,10,50)
a[np.where((a%2 == 0) & (a%5==0) & (a!=0))] 

array([], dtype=int64)

In [34]:
# Знаходимо індекси значень, що задовільняють умову
index = np.where(((a % 2 == 0) & (a % 5==0) & (a !=0) ))

#Перевіряємо і виводимо значень, що задовільняють умову, якщо вони існують

if index[0].size > 0:
    print(a[index])
else:
    print('Значеня, які б задовілняли умову, не існує в масиві')

Значеня, які б задовілняли умову, не існує в масиві


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [20]:
# Функція linalg.solve() вирішує лінійні рівння або систему лінійних рівнняь

# Задаємо матрицю a - матриця коефіцієнтів
a = np.array([[2, 5],
    [1, -10]])

# Задаємо матрицю b - матриця вільних членів рівняння 
b = np.array([1, 3])

# Знаходимо розвязок системи рівнянь
res = np.linalg.solve(a, b) 
x = res[0]
y = res[1]
print(f'x = {x}, y = {y}')

x = 1.0, y = -0.2


In [21]:
# Перевірка результату: перемножумо матрицю коефіцієнтів на стовпець з реультатами

checking = np.dot(a, res)

# Даний добуток повиннен матриці вільних членів b

if checking.all() == b.all():
    print("Рішення вірне")

Рішення вірне
